---

- name:
    "Ensure Emacs is installed | {{ emacs_wayland | ternary('Wayland', 'X') }}"
  community.general.pkgng:
    state: present
    name: "{{ emacs_wayland | ternary('emacs-wayland', 'emacs') }}"
    autoremove: true
    cached: false
  become: true

- name: Clone Doom Emacs
  ansible.builtin.git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d
    version: master
    depth: 1
    update: false
  notify:
    - Synchronize Doom Emacs
