---

name: CI
'on':
  pull_request:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: lint
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pip3 install yamllint
      - run: yamllint .
      - run: ansible-galaxy collection build
      - run: >-
          ansible-galaxy collection install
          charlesrocket-freebsd-$(grep version galaxy.yml |
          awk '{print $2}').tar.gz

      - uses: ansible/ansible-lint@main

  ansible-test:
    name: ansible-test
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: sanity

  molecule:
    name: test ${{ matrix.scenario }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
          - server

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
          check-latest: true

      - name: Add vagrant package
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | \
            sudo gpg --dearmor -o \
            /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) \
            signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
            https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox vagrant
          pip install -r requirements-dev.txt

      - name: Cache Vagrant boxes
        uses: actions/cache@v4
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.scenario }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.scenario }}

      - name: Run Molecule
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: freebsd14

  release:
    needs: [ansible-test, molecule]
    permissions:
      contents: read
      pages: write
      id-token: write

    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/cd.yml
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
